services:
  - type: web
    name: invoice-management-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - build.js
        - server.js 